# [PracticumProject]

In [ ]:
USE [master]
GO

In [ ]:
/****** Object:  Database [PracticumProject]    Script Date: 15/02/2023 21:05:00 ******/
/*run to have data of health insurance funds and users*/
CREATE DATABASE [PracticumProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PracticumProject', FILENAME = N'C:\Users\הודיה\PracticumProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PracticumProject_log', FILENAME = N'C:\Users\הודיה\PracticumProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PracticumProject] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PracticumProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PracticumProject] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PracticumProject] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PracticumProject] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PracticumProject] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PracticumProject] SET ARITHABORT OFF 
GO
ALTER DATABASE [PracticumProject] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PracticumProject] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PracticumProject] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PracticumProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PracticumProject] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PracticumProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PracticumProject] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PracticumProject] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PracticumProject] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PracticumProject] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PracticumProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PracticumProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PracticumProject] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PracticumProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PracticumProject] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PracticumProject] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [PracticumProject] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PracticumProject] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PracticumProject] SET  MULTI_USER 
GO
ALTER DATABASE [PracticumProject] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PracticumProject] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PracticumProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PracticumProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PracticumProject] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PracticumProject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PracticumProject] SET QUERY_STORE = OFF
GO

# [dbo].[__EFMigrationsHistory]

In [ ]:
USE [PracticumProject]
GO

In [ ]:
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 15/02/2023 21:05:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[HMOs]

In [ ]:
/****** Object:  Table [dbo].[HMOs]    Script Date: 15/02/2023 21:05:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HMOs](
	[IdHMO] [int] IDENTITY(1,1) NOT NULL,
	[HMOName] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_HMOs] PRIMARY KEY CLUSTERED 
(
	[IdHMO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[People]

In [ ]:
/****** Object:  Table [dbo].[People]    Script Date: 15/02/2023 21:05:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[People](
	[PersonId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](max) NOT NULL,
	[LastName] [nvarchar](max) NOT NULL,
	[IdNumber] [nvarchar](9) NOT NULL,
	[DateOfBirth] [datetime2](7) NOT NULL,
	[IsMale] [bit] NOT NULL,
	[HMOId] [int] NULL,
	[ParentId] [int] NULL,
 CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[__EFMigrationsHistory]

In [ ]:
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20230214224012_init', N'7.0.3')
GO

# [dbo].[HMOs]

In [ ]:
SET IDENTITY_INSERT [dbo].[HMOs] ON 
INSERT [dbo].[HMOs] ([IdHMO], [HMOName]) VALUES (1, N'מכבי')
INSERT [dbo].[HMOs] ([IdHMO], [HMOName]) VALUES (2, N'כללית')
INSERT [dbo].[HMOs] ([IdHMO], [HMOName]) VALUES (3, N'מאוחדת')
INSERT [dbo].[HMOs] ([IdHMO], [HMOName]) VALUES (4, N'לאומית')
INSERT [dbo].[HMOs] ([IdHMO], [HMOName]) VALUES (5, N'אחר')
SET IDENTITY_INSERT [dbo].[HMOs] OFF
GO

# [dbo].[People]

In [ ]:
SET IDENTITY_INSERT [dbo].[People] ON 
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (2, N'דניאל', N'שלומוב', N'254136987', CAST(N'2023-02-09T22:00:00.0000000' AS DateTime2), 1, 4, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (3, N'ציון', N'יקר', N'999999999', CAST(N'2023-01-31T22:00:00.0000000' AS DateTime2), 1, 3, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (4, N'שלמה', N'יקר', N'888888888', CAST(N'2023-02-08T22:00:00.0000000' AS DateTime2), 1, 3, 3)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (5, N'אמא', N'יקרה', N'666666666', CAST(N'2023-02-14T22:52:33.2470000' AS DateTime2), 0, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (6, N'ברכי', N'יקרה', N'444444444', CAST(N'2023-02-08T22:00:00.0000000' AS DateTime2), 0, 2, 5)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (7, N'ילדה', N'יקרה', N'555555555', CAST(N'2023-02-06T22:00:00.0000000' AS DateTime2), 1, 2, 5)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (8, N'רבקי', N'אליהו ', N'111111156', CAST(N'2023-02-14T22:55:05.6350000' AS DateTime2), 0, 3, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (9, N'ריקי', N'אליהו ', N'845632562', CAST(N'2023-02-08T22:00:00.0000000' AS DateTime2), 0, 3, 8)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (10, N'שושי', N'אליהו ', N'323168465', CAST(N'2023-02-02T22:00:00.0000000' AS DateTime2), 0, 3, 8)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (11, N'פרי', N'אליהו ', N'131848942', CAST(N'2023-02-14T22:55:59.3010000' AS DateTime2), 0, 3, 8)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (12, N'נחמי', N'אליהו ', N'223168489', CAST(N'2023-02-14T22:55:52.3490000' AS DateTime2), 0, 3, 8)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (13, N'מירי', N'כהן', N'458755845', CAST(N'2023-02-01T22:00:00.0000000' AS DateTime2), 0, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (14, N'דוד', N'כהן', N'999995299', CAST(N'2023-01-31T22:00:00.0000000' AS DateTime2), 1, 2, 13)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (15, N'שרי', N'כהן', N'164313878', CAST(N'2023-02-14T23:00:15.7440000' AS DateTime2), 0, 2, 13)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (16, N'רות', N'לוי', N'165435784', CAST(N'2023-02-14T23:01:17.1240000' AS DateTime2), 0, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (17, N'ציפי', N'כץ', N'784955622', CAST(N'2023-02-14T23:02:09.4120000' AS DateTime2), 0, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (18, N'הודיה', N'שלומוב', N'565467684', CAST(N'2023-02-14T23:03:53.9960000' AS DateTime2), 0, 3, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (19, N'אברהם', N'שלומוב', N'849576213', CAST(N'2023-02-02T22:00:00.0000000' AS DateTime2), 1, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (20, N'רותי', N'שלומוב', N'461325978', CAST(N'2023-02-14T23:16:27.3890000' AS DateTime2), 0, 2, 19)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (21, N'שמואל', N'שלומוב', N'195876423', CAST(N'2023-02-13T22:00:00.0000000' AS DateTime2), 1, 2, 19)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (22, N'חזקי', N'שלומוב', N'999444423', CAST(N'2023-02-13T22:00:00.0000000' AS DateTime2), 1, 2, 19)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (23, N'יעל', N'שלומוב', N'555584444', CAST(N'2023-02-06T22:00:00.0000000' AS DateTime2), 0, 2, 19)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (24, N'מיכאל', N'לוי', N'748156888', CAST(N'2023-01-31T22:00:00.0000000' AS DateTime2), 1, 3, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (25, N'שרי', N'לוי', N'186468513', CAST(N'2023-02-13T22:00:00.0000000' AS DateTime2), 0, 3, 24)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (26, N'יוסי', N'לוי', N'112255448', CAST(N'2023-02-07T22:00:00.0000000' AS DateTime2), 1, 3, 24)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (29, N'דוד', N'שלומוב', N'643549999', CAST(N'2023-01-31T22:00:00.0000000' AS DateTime2), 1, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (31, N'הודיה', N'שלומוב', N'444444383', CAST(N'2023-02-07T22:00:00.0000000' AS DateTime2), 0, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (32, N'שרי', N'לוי', N'867585875', CAST(N'2023-02-07T22:00:00.0000000' AS DateTime2), 0, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (33, N'אבי', N'גך', N'670987655', CAST(N'2023-02-01T22:00:00.0000000' AS DateTime2), 1, 3, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (35, N'גיטי', N'מין', N'635797654', CAST(N'2023-01-31T22:00:00.0000000' AS DateTime2), 0, 5, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (36, N'ילד', N'חמוד', N'444555662', CAST(N'2023-02-02T22:00:00.0000000' AS DateTime2), 1, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (37, N'שרי', N'לוי', N'445588774', CAST(N'2023-02-01T22:00:00.0000000' AS DateTime2), 0, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (38, N'דוד', N'כהן', N'784956132', CAST(N'2023-01-31T22:00:00.0000000' AS DateTime2), 1, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (39, N'יעל', N'לוי', N'785549999', CAST(N'2023-01-31T22:00:00.0000000' AS DateTime2), 0, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (49, N'רחלי', N'פורת', N'164513494', CAST(N'2023-02-08T22:00:00.0000000' AS DateTime2), 0, 3, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (50, N'שולמית', N'כהן', N'157563333', CAST(N'2023-02-01T22:00:00.0000000' AS DateTime2), 0, 2, NULL)
INSERT [dbo].[People] ([PersonId], [FirstName], [LastName], [IdNumber], [DateOfBirth], [IsMale], [HMOId], [ParentId]) VALUES (51, N'רחלי', N'פלאי', N'165195565', CAST(N'2023-02-08T22:00:00.0000000' AS DateTime2), 0, 3, NULL)
SET IDENTITY_INSERT [dbo].[People] OFF
GO

# [IX_People_HMOId]

In [ ]:
/****** Object:  Index [IX_People_HMOId]    Script Date: 15/02/2023 21:05:00 ******/
CREATE NONCLUSTERED INDEX [IX_People_HMOId] ON [dbo].[People]
(
	[HMOId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [IX_People_ParentId]

In [ ]:
/****** Object:  Index [IX_People_ParentId]    Script Date: 15/02/2023 21:05:00 ******/
CREATE NONCLUSTERED INDEX [IX_People_ParentId] ON [dbo].[People]
(
	[ParentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [FK_People_HMOs_HMOId]

In [ ]:
ALTER TABLE [dbo].[People]  WITH CHECK ADD  CONSTRAINT [FK_People_HMOs_HMOId] FOREIGN KEY([HMOId])
REFERENCES [dbo].[HMOs] ([IdHMO])
GO
ALTER TABLE [dbo].[People] CHECK CONSTRAINT [FK_People_HMOs_HMOId]
GO

# [FK_People_People_ParentId]

In [ ]:
ALTER TABLE [dbo].[People]  WITH CHECK ADD  CONSTRAINT [FK_People_People_ParentId] FOREIGN KEY([ParentId])
REFERENCES [dbo].[People] ([PersonId])
GO
ALTER TABLE [dbo].[People] CHECK CONSTRAINT [FK_People_People_ParentId]
GO

# [PracticumProject]

In [ ]:
USE [master]
GO

In [ ]:
ALTER DATABASE [PracticumProject] SET  READ_WRITE 
GO